var mongoose = require("mongoose");
    Thread = require("threads.js");

var seedData = [
{
    title: "Diet control in order to improve eye sight",
    date: Date,
    author: "Dr. Shah",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac egestas urna. Nam eu odio sem. In fermentum sed arcu vel fringilla. Vivamus non leo massa. Nam eget enim sit amet augue vulputate gravida ut at libero. Vestibulum interdum dolor imperdiet, dictum ipsum vitae, euismod lacus. Fusce arcu sapien, eleifend auctor facilisis sed, molestie eget ante. In laoreet elit quis urna varius pretium. Proin ac odio vitae quam ultricies vulputate.Mauris auctor magna turpis, ac consequat leo scelerisque sed. Donec suscipit ultricies maximus. Vestibulum laoreet neque tortor. Donec molestie eu dolor nec malesuada. Donec lacinia nunc et justo elementum lobortis. Pellentesque sed massa venenatis, aliquam nisl sit amet, finibus lorem. Phasellus purus nulla, condimentum sed suscipit vel, lobortis sit amet eros. Duis auctor gravida lorem non vulputate. Sed ultricies sodales tortor, tempus sollicitudin elit hendrerit sit amet. Mauris in urna massa. Fusce aliquet aliquet sem, sed maximus lectus elementum euismod. Ut est felis, mattis sit amet urna non, luctus condimentum sapien. Aliquam et orci urna. Aenean eget luctus nunc. Nunc maximus dictum feugiat. Vestibulum quis lacus sagittis, sollicitudin metus a, ultricies risus. Aliquam euismod libero quam, nec suscipit neque sagittis a. Maecenas eu facilisis nulla. Vestibulum sit amet faucibus sapien, at hendrerit lacus. Duis imperdiet commodo elit, vitae egestas mi rutrum vitae. Aliquam tempus ex turpis, lobortis ornare augue egestas quis. Suspendisse ultricies porttitor mauris nec fringilla. Integer sed lectus sit amet mauris viverra faucibus sed nec eros. Aliquam ut mollis tortor, sed cursus arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis efficitur venenatis sapien, eget ultricies sem. Aliquam ac tellus dui. Pellentesque nec augue at ex ullamcorper placerat."
},
{
    title: "Having a great heart!",
    date: Date,
    author: "Dr. Batra",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac egestas urna. Nam eu odio sem. In fermentum sed arcu vel fringilla. Vivamus non leo massa. Nam eget enim sit amet augue vulputate gravida ut at libero. Vestibulum interdum dolor imperdiet, dictum ipsum vitae, euismod lacus. Fusce arcu sapien, eleifend auctor facilisis sed, molestie eget ante. In laoreet elit quis urna varius pretium. Proin ac odio vitae quam ultricies vulputate.Mauris auctor magna turpis, ac consequat leo scelerisque sed. Donec suscipit ultricies maximus. Vestibulum laoreet neque tortor. Donec molestie eu dolor nec malesuada. Donec lacinia nunc et justo elementum lobortis. Pellentesque sed massa venenatis, aliquam nisl sit amet, finibus lorem. Phasellus purus nulla, condimentum sed suscipit vel, lobortis sit amet eros. Duis auctor gravida lorem non vulputate. Sed ultricies sodales tortor, tempus sollicitudin elit hendrerit sit amet. Mauris in urna massa. Fusce aliquet aliquet sem, sed maximus lectus elementum euismod. Ut est felis, mattis sit amet urna non, luctus condimentum sapien. Aliquam et orci urna. Aenean eget luctus nunc. Nunc maximus dictum feugiat. Vestibulum quis lacus sagittis, sollicitudin metus a, ultricies risus. Aliquam euismod libero quam, nec suscipit neque sagittis a. Maecenas eu facilisis nulla. Vestibulum sit amet faucibus sapien, at hendrerit lacus. Duis imperdiet commodo elit, vitae egestas mi rutrum vitae. Aliquam tempus ex turpis, lobortis ornare augue egestas quis. Suspendisse ultricies porttitor mauris nec fringilla. Integer sed lectus sit amet mauris viverra faucibus sed nec eros. Aliquam ut mollis tortor, sed cursus arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis efficitur venenatis sapien, eget ultricies sem. Aliquam ac tellus dui. Pellentesque nec augue at ex ullamcorper placerat."
},
{
    title: "Symptoms of cardiac arrest",
    date: Date,
    author: "Dr. Agarwal",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac egestas urna. Nam eu odio sem. In fermentum sed arcu vel fringilla. Vivamus non leo massa. Nam eget enim sit amet augue vulputate gravida ut at libero. Vestibulum interdum dolor imperdiet, dictum ipsum vitae, euismod lacus. Fusce arcu sapien, eleifend auctor facilisis sed, molestie eget ante. In laoreet elit quis urna varius pretium. Proin ac odio vitae quam ultricies vulputate.Mauris auctor magna turpis, ac consequat leo scelerisque sed. Donec suscipit ultricies maximus. Vestibulum laoreet neque tortor. Donec molestie eu dolor nec malesuada. Donec lacinia nunc et justo elementum lobortis. Pellentesque sed massa venenatis, aliquam nisl sit amet, finibus lorem. Phasellus purus nulla, condimentum sed suscipit vel, lobortis sit amet eros. Duis auctor gravida lorem non vulputate. Sed ultricies sodales tortor, tempus sollicitudin elit hendrerit sit amet. Mauris in urna massa. Fusce aliquet aliquet sem, sed maximus lectus elementum euismod. Ut est felis, mattis sit amet urna non, luctus condimentum sapien. Aliquam et orci urna. Aenean eget luctus nunc. Nunc maximus dictum feugiat. Vestibulum quis lacus sagittis, sollicitudin metus a, ultricies risus. Aliquam euismod libero quam, nec suscipit neque sagittis a. Maecenas eu facilisis nulla. Vestibulum sit amet faucibus sapien, at hendrerit lacus. Duis imperdiet commodo elit, vitae egestas mi rutrum vitae. Aliquam tempus ex turpis, lobortis ornare augue egestas quis. Suspendisse ultricies porttitor mauris nec fringilla. Integer sed lectus sit amet mauris viverra faucibus sed nec eros. Aliquam ut mollis tortor, sed cursus arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis efficitur venenatis sapien, eget ultricies sem. Aliquam ac tellus dui. Pellentesque nec augue at ex ullamcorper placerat."
}
];

function seedDB(){
    //Create User
}